import type { Metadata } from "next";
import "./style/globals.css";
import { baseFont } from "./style/localFonts";

export const metadata: Metadata = {
  title: "Recipe GPT Optimizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={baseFont.className}>{children}</body>
    </html>
  );
}
